# Generated by Django 6.0.3 on 2026-04-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='assessment',
            name='passing_percentage',
            field=models.FloatField(default=50.0, help_text='Minimum % to pass'),
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=100)),
                ('a_min', models.FloatField(default=90, help_text='Minimum % for A')),
                ('b_min', models.FloatField(default=80, help_text='Minimum % for B')),
                ('c_min', models.FloatField(default=70, help_text='Minimum % for C')),
                ('d_min', models.FloatField(default=60, help_text='Minimum % for D')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.gradingscheme'),
        ),
    ]
