# Generated by Django 6.0.3 on 2026-04-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.CharField(blank=True, help_text='e.g. course name for tuition fees', max_length=200),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
